# Generated by Django 2.2 on 2020-07-25 00:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobileBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AutomobileKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AutomobileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImmobileKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImmobileAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('url_origin', models.URLField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_auction', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.City')),
                ('kind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.ImmobileKind')),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Neighborhood')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Seller')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('url_origin', models.URLField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_auction', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.AutomobileBrand')),
                ('kind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.AutomobileKind')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.AutomobileModel')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Seller')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Status')),
            ],
        ),
    ]
