# Generated by Django 2.2 on 2020-07-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.AutomobileBrand'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='automobile_pics'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.AutomobileKind'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.AutomobileModel'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Seller'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Status'),
        ),
        migrations.AlterField(
            model_name='immobileauction',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.City'),
        ),
        migrations.AlterField(
            model_name='immobileauction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='immobile_pics'),
        ),
        migrations.AlterField(
            model_name='immobileauction',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ImmobileKind'),
        ),
        migrations.AlterField(
            model_name='immobileauction',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='immobileauction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Seller'),
        ),
        migrations.AlterField(
            model_name='immobileauction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Status'),
        ),
    ]
