# Generated by Django 2.2 on 2020-07-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200726_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImmobileAuction',
            new_name='Immobile',
        ),
    ]
