# Generated by Django 2.2 on 2020-07-26 22:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200726_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[250, 150], upload_to='automobile_pics'),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[250, 150], upload_to='immobile_pics'),
        ),
    ]
