# Generated by Django 2.2 on 2020-07-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200726_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='automobile_pics'),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='immobile_pics'),
        ),
    ]
