# Generated by Django 2.2 on 2020-07-27 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20200727_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobile',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
